### ISSUE TITLE
模型测试预测全是5PJ0

### ISSUE THREAD

**Issue by 0Jvang** [Xpp521/CNN_Captcha#4]
你好，使用了你的项目，遇到一点问题，就是我训练了一个20000次的模型，但在模型测试的全部100次测试中，预测值全为5PJ0，请问会是哪里的问题呢

**Comment by Xpp521** [comment]
我简单训练了几千次，虽然准确率不高，但是没出现这种情况。
![Snipaste_2020-05-28_20-08-47](https://user-images.githubusercontent.com/39331061/83139743-6cd24880-a11f-11ea-8a6e-a0c620e29435.jpg)
检查一下，是不是第三方库的版本问题。
我的库版本（Python 3.7）：
- pyperclip==1.8.0
- requests==2.23.0
- numpy==1.18.4
- Pillow==5.3.0
- PyQt4==4.11.4
- tensorflow==1.14.0
- captcha==0.3
PS：训练模型的时候tensorflow这个库最好用gpu版，cpu版比较慢。

**Comment by ZzzZHuXIao** [comment]
> 你好，使用了你的项目，遇到一点问题，就是我训练了一个20000次的模型，但在模型测试的全部100次测试中，预测值全为5PJ0，请问会是哪里的问题呢

您好，我也遇到了同您一样的问题，请问您最后是如何解决的呢？

**Comment by 0Jvang** [comment]
不好意思我搞忘了，好像是代码的问题，我有空再看一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月18日(星期五) 下午2:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Xpp521/CNN_Captcha] 模型测试预测全是5PJ0 (#4)





  
你好，使用了你的项目，遇到一点问题，就是我训练了一个20000次的模型，但在模型测试的全部100次测试中，预测值全为5PJ0，请问会是哪里的问题呢
  
您好，我也遇到了同您一样的问题，请问您最后是如何解决的呢？

**Comment by 0Jvang** [comment]
好像是因为模型训练完后没有点保存模型




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Xpp521/CNN_Captcha"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月18日(星期五) 下午2:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Xpp521/CNN_Captcha] 模型测试预测全是5PJ0 (#4)





  
你好，使用了你的项目，遇到一点问题，就是我训练了一个20000次的模型，但在模型测试的全部100次测试中，预测值全为5PJ0，请问会是哪里的问题呢
  
您好，我也遇到了同您一样的问题，请问您最后是如何解决的呢？

**Comment by 0Jvang** [comment]
模型训练完后未点保存
